on:
  workflow_dispatch:
  schedule:
    - cron: 45 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout self
        uses: actions/checkout@v3
      - id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: checkout luckysheet
        uses: actions/checkout@v3
        with:
          repository: mengshukeji/Luckysheet
          path: luckysheet
      - name: checkout luckysheet-locale-ja
        uses: actions/checkout@v3
        with:
          repository: luncheon/luckysheet-locale-ja
          path: luckysheet-locale-ja
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --cwd luckysheet/
      - run: yarn --cwd luckysheet/ run build
      - run: rm -rf assets/ demo/ locales/
      - run: node scripts/build-without-locales.mjs
      - run: cp -r luckysheet/dist/demoData demo/
      - run: cp luckysheet/LICENSE .
      - name: check changes
        run: echo "::set-output name=count::$(git status --porcelain | wc -l)"
        id: changes
      - name: push
        if: steps.changes.outputs.count > 0
        run: |
          node scripts/package.json.mjs
          git config --global user.name "luncheon"
          git config --global user.email "takeuck+github@gmail.com"
          git add .
          git commit -m "${{ steps.date.outputs.date }}"
          git tag -f "${{ steps.date.outputs.date }}"
          git push -f --tags origin main
